name: Add Vite setup

on:
  workflow_dispatch:

jobs:
  add-vite-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Create files for Vite setup
        run: |
          set -e
          mkdir -p src

          cat > package.json <<'EOF'
{
  "name": "bk4301fl",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "typescript": "^5.1.6",
    "vite": "^5.0.0",
    "@vitejs/plugin-react": "^3.0.0"
  }
}
EOF

          cat > tsconfig.json <<'EOF'
{
  "compilerOptions": {
    "target": "ES2021",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "types": ["vite/client"]
  },
  "include": ["src", "./**/*.ts", "./**/*.tsx"]
}
EOF

          cat > vite.config.ts <<'EOF'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173
  }
})
EOF

          cat > src/main.tsx <<'EOF'
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from '../App'
import '../index.css'

const rootElement = document.getElementById('root')
if (!rootElement) {
  throw new Error('Could not find root element to mount to')
}

const root = ReactDOM.createRoot(rootElement)
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)

// Register Service Worker for PWA/Offline capability
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js')
      .then((registration) => {
        console.log('ServiceWorker registration successful with scope: ', registration.scope)
      })
      .catch((err) => {
        console.log('ServiceWorker registration failed: ', err)
      })
  })
}
EOF

          cat > index.html <<'EOF'
<!DOCTYPE html>
<html lang="zh-TW">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#047857" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="description" content="BK4301FL 專業指南 - 離線可用，隨時學習" />
    <title>BK4301FL 專業指南</title>
    <link rel="manifest" href="/manifest.json" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@300;400;500;700&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Noto Sans TC', sans-serif;
        overscroll-behavior-y: none; /* Prevent pull-to-refresh on mobile */
      }
      /* Custom scrollbar for chat */
      .scrollbar-hide::-webkit-scrollbar {
          display: none;
      }
      .scrollbar-hide {
          -ms-overflow-style: none;
          scrollbar-width: none;
      }
      @keyframes slide-down {
        from { transform: translateY(-10px); opacity: 0; }
        to { transform: translateY(0); opacity: 1; }
      }
      .animate-slide-down {
        animation: slide-down 0.3s ease-out forwards;
      }
      @keyframes fade-in {
        from { opacity: 0; transform: translateY(5px); }
        to { opacity: 1; transform: translateY(0); }
      }
      .animate-fade-in {
        animation: fade-in 0.4s ease-out forwards;
      }
      
      /* Startup Splash Animations */
      @keyframes zoom-fade-in {
        0% { transform: scale(0.8); opacity: 0; }
        100% { transform: scale(1); opacity: 1; }
      }
      .animate-zoom-fade-in {
        animation: zoom-fade-in 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards;
      }
      
      @keyframes splash-exit {
        0% { opacity: 1; visibility: visible; }
        100% { opacity: 0; visibility: hidden; }
      }
      .animate-splash-exit {
        animation: splash-exit 0.5s ease-in-out forwards;
      }
    </style>
<link rel="stylesheet" href="/index.css">
</head>
  <body class="bg-slate-50 text-slate-800">
    <div id="root"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>
EOF

          cat > .gitignore <<'EOF'
node_modules
dist
.vite
.env
.env.local
EOF

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: add Vite dev setup"

      - name: Push branch
        run: |
          BRANCH=add-vite-setup
          git push -u origin HEAD:refs/heads/$BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: add Vite dev setup"
          title: "chore: add Vite dev setup"
          body: |
            新增 Vite 開發環境設定以支援本地開發與生產建置：

            - 新增 package.json（scripts: dev/build/preview）
            - 新增 tsconfig.json、vite.config.ts
            - 新增 src/main.tsx，並將專案入口指向 /src/main.tsx
            - 更新 index.html 為 Vite 友善版本（移除 importmap，使用 module entry）
            - 新增 .gitignore

            測試步驟：
            1. npm install
            2. npm run dev → 開啟 http://localhost:5173
            3. npm run build / npm run preview
          base: main
          head: add-vite-setup
          labels: "chore,infra"
